### PR TITLE
WIP: Discuss how to get fetching to work on dev machine

### PR DESCRIPTION
**Pull request by klahnakoski**

### CODE REVIEW

**Comment by klahnakoski** [comment]
@armenzg  this is a work-in-progress.  Really, just some code to focus the discussion.  I changed the code so I could use my own emal/api key.

How do I get this code to run on my development machine?

```
C:\Users\kyle\code\firefox-health-backend>yarn build
yarn run v1.13.0
$ neutrino build
√ Building project completed
Hash: 9633675f7742390fc5f0
Version: webpack 3.12.0
Time: 3141ms
             Asset     Size  Chunks             Chunk Names
          index.js  66.1 kB       0  [emitted]  index
    nimbledroid.js    14 kB       1  [emitted]  nimbledroid
      index.js.map   108 kB       0  [emitted]  index
nimbledroid.js.map  15.9 kB       1  [emitted]  nimbledroid
Done in 6.50s.

C:\Users\kyle\code\firefox-health-backend>resources\fetchNimbledroidData.bat

C:\Users\kyle\code\firefox-health-backend>set NIMBLEDROID_EMAIL=klahnakoski@mozilla.com

C:\Users\kyle\code\firefox-health-backend>set NIMBLEDROID_API_KEY=0000000

C:\Users\kyle\code\firefox-health-backend>set REDIS_URL=redis://localhost:6379

C:\Users\kyle\code\firefox-health-backend>node build\nimbledroid.js

C:\Users\kyle\code\firefox-health-backend>
```
Running it through the debugger: each of the nimbledroid calls returns `[\n\n]`, which is nothing.

**Comment by armenzg** [comment]
Use [dotenv](https://www.npmjs.com/package/dotenv). It is quite widely used.

Don't use |yarn build| but |yarn start|

**Comment by klahnakoski** [comment]
I attempted the `yarn start` strategy, but it seems I must still run the 


```
C:\Users\kyle\code\firefox-health-backend>yarn start
yarn run v1.13.0
$ neutrino start
√ Build completed
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md build\index.js:926:5
http://:::3000/ in development

  Error: The script that fetches data should have run before hitting the API.
      at C:\Users\kyle\code\firefox-health-backend\src\utils\apis\queryNimbledroidData.js:53:11
      at Generator.next (<anonymous>)
      at step (C:\Users\kyle\code\firefox-health-backend\build\index.js:2580:191)
      at C:\Users\kyle\code\firefox-health-backend\build\index.js:2580:361
      at process.internalTickCallback (internal/process/next_tick.js:77:7)

```

**Comment by klahnakoski** [comment]
@armenzg got the api key from npark.  attempting to use it now...

**Pull request closed without merging**
